export interface Language {
  code: string;
  name: string;
  englishName: string;
}

export const POPULAR_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', englishName: 'English' },
  { code: 'ro', name: 'Română', englishName: 'Romanian' },
  { code: 'es', name: 'Español', englishName: 'Spanish' },
  { code: 'fr', name: 'Français', englishName: 'French' },
  { code: 'de', name: 'Deutsch', englishName: 'German' },
  { code: 'it', name: 'Italiano', englishName: 'Italian' },
];

export const ALL_LANGUAGES: Language[] = [
  ...POPULAR_LANGUAGES,
  { code: 'af', name: 'Afrikaans', englishName: 'Afrikaans' },
  { code: 'sq', name: 'Shqip', englishName: 'Albanian' },
  { code: 'am', name: 'አማርኛ', englishName: 'Amharic' },
  { code: 'ar', name: 'العربية', englishName: 'Arabic' },
  { code: 'hy', name: 'Հայերեն', englishName: 'Armenian' },
  { code: 'az', name: 'Azərbaycan', englishName: 'Azerbaijani' },
  { code: 'eu', name: 'Euskara', englishName: 'Basque' },
  { code: 'be', name: 'Беларуская', englishName: 'Belarusian' },
  { code: 'bn', name: 'বাংলা', englishName: 'Bengali' },
  { code: 'bs', name: 'Bosanski', englishName: 'Bosnian' },
  { code: 'bg', name: 'Български', englishName: 'Bulgarian' },
  { code: 'ca', name: 'Català', englishName: 'Catalan' },
  { code: 'ceb', name: 'Cebuano', englishName: 'Cebuano' },
  { code: 'zh', name: '中文 (Simplified)', englishName: 'Chinese (Simplified)' },
  { code: 'zh-TW', name: '中文 (Traditional)', englishName: 'Chinese (Traditional)' },
  { code: 'co', name: 'Corsu', englishName: 'Corsican' },
  { code: 'hr', name: 'Hrvatski', englishName: 'Croatian' },
  { code: 'cs', name: 'Čeština', englishName: 'Czech' },
  { code: 'da', name: 'Dansk', englishName: 'Danish' },
  { code: 'nl', name: 'Nederlands', englishName: 'Dutch' },
  { code: 'eo', name: 'Esperanto', englishName: 'Esperanto' },
  { code: 'et', name: 'Eesti', englishName: 'Estonian' },
  { code: 'fi', name: 'Suomi', englishName: 'Finnish' },
  { code: 'gl', name: 'Galego', englishName: 'Galician' },
  { code: 'ka', name: 'ქართული', englishName: 'Georgian' },
  { code: 'el', name: 'Ελληνικά', englishName: 'Greek' },
  { code: 'gu', name: 'ગુજરાતી', englishName: 'Gujarati' },
  { code: 'ht', name: 'Kreyòl Ayisyen', englishName: 'Haitian Creole' },
  { code: 'ha', name: 'Hausa', englishName: 'Hausa' },
  { code: 'he', name: 'עברית', englishName: 'Hebrew' },
  { code: 'hi', name: 'हिन्दी', englishName: 'Hindi' },
  { code: 'hmn', name: 'Hmoob', englishName: 'Hmong' },
  { code: 'hu', name: 'Magyar', englishName: 'Hungarian' },
  { code: 'is', name: 'Íslenska', englishName: 'Icelandic' },
  { code: 'ig', name: 'Igbo', englishName: 'Igbo' },
  { code: 'id', name: 'Bahasa Indonesia', englishName: 'Indonesian' },
  { code: 'ga', name: 'Gaeilge', englishName: 'Irish' },
  { code: 'ja', name: '日本語', englishName: 'Japanese' },
  { code: 'jv', name: 'Basa Jawa', englishName: 'Javanese' },
  { code: 'kn', name: 'ಕನ್ನಡ', englishName: 'Kannada' },
  { code: 'kk', name: 'Қазақ тілі', englishName: 'Kazakh' },
  { code: 'km', name: 'ខ្មែរ', englishName: 'Khmer' },
  { code: 'ko', name: '한국어', englishName: 'Korean' },
  { code: 'ku', name: 'Kurdî', englishName: 'Kurdish' },
  { code: 'ky', name: 'Кыргызча', englishName: 'Kyrgyz' },
  { code: 'lo', name: 'ລາວ', englishName: 'Lao' },
  { code: 'lv', name: 'Latviešu', englishName: 'Latvian' },
  { code: 'lt', name: 'Lietuvių', englishName: 'Lithuanian' },
  { code: 'lb', name: 'Lëtzebuergesch', englishName: 'Luxembourgish' },
  { code: 'mk', name: 'Македонски', englishName: 'Macedonian' },
  { code: 'mg', name: 'Malagasy', englishName: 'Malagasy' },
  { code: 'ms', name: 'Bahasa Melayu', englishName: 'Malay' },
  { code: 'ml', name: 'മലയാളം', englishName: 'Malayalam' },
  { code: 'mt', name: 'Malti', englishName: 'Maltese' },
  { code: 'mi', name: 'Māori', englishName: 'Maori' },
  { code: 'mr', name: 'मराठी', englishName: 'Marathi' },
  { code: 'mn', name: 'Монгол', englishName: 'Mongolian' },
  { code: 'my', name: 'Burmese', englishName: 'Myanmar (Burmese)' },
  { code: 'ne', name: 'नेपाली', englishName: 'Nepali' },
  { code: 'no', name: 'Norsk', englishName: 'Norwegian' },
  { code: 'ny', name: 'Nyanja', englishName: 'Nyanja (Chichewa)' },
  { code: 'ps', name: 'Pashto', englishName: 'Pashto' },
  { code: 'fa', name: 'فارسی', englishName: 'Persian' },
  { code: 'pl', name: 'Polski', englishName: 'Polish' },
  { code: 'pt', name: 'Português', englishName: 'Portuguese' },
  { code: 'pa', name: 'Punjabi', englishName: 'Punjabi' },
  { code: 'ru', name: 'Русский', englishName: 'Russian' },
  { code: 'sm', name: 'Samoan', englishName: 'Samoan' },
  { code: 'gd', name: 'Gàidhlig', englishName: 'Scots Gaelic' },
  { code: 'sr', name: 'Српски', englishName: 'Serbian' },
  { code: 'st', name: 'Sesotho', englishName: 'Sesotho' },
  { code: 'sn', name: 'Shona', englishName: 'Shona' },
  { code: 'sd', name: 'Sindhi', englishName: 'Sindhi' },
  { code: 'si', name: 'Sinhala', englishName: 'Sinhala' },
  { code: 'sk', name: 'Slovenčina', englishName: 'Slovak' },
  { code: 'sl', name: 'Slovenščina', englishName: 'Slovenian' },
  { code: 'so', name: 'Somali', englishName: 'Somali' },
  { code: 'su', name: 'Sundanese', englishName: 'Sundanese' },
  { code: 'sw', name: 'Kiswahili', englishName: 'Swahili' },
  { code: 'sv', name: 'Svenska', englishName: 'Swedish' },
  { code: 'tl', name: 'Tagalog', englishName: 'Tagalog (Filipino)' },
  { code: 'tg', name: 'Тоҷикӣ', englishName: 'Tajik' },
  { code: 'ta', name: 'தமிழ்', englishName: 'Tamil' },
  { code: 'te', name: 'తెలుగు', englishName: 'Telugu' },
  { code: 'th', name: 'ไทย', englishName: 'Thai' },
  { code: 'tr', name: 'Türkçe', englishName: 'Turkish' },
  { code: 'uk', name: 'Українська', englishName: 'Ukrainian' },
  { code: 'ur', name: 'Urdu', englishName: 'Urdu' },
  { code: 'uz', name: 'Oʻzbek', englishName: 'Uzbek' },
  { code: 'vi', name: 'Tiếng Việt', englishName: 'Vietnamese' },
  { code: 'cy', name: 'Cymraeg', englishName: 'Welsh' },
  { code: 'xh', name: 'Xhosa', englishName: 'Xhosa' },
  { code: 'yi', name: 'Yiddish', englishName: 'Yiddish' },
  { code: 'yo', name: 'Yorùbá', englishName: 'Yoruba' },
  { code: 'zu', name: 'Zulu', englishName: 'Zulu' },
];

// Helper to remove duplicates if POPULAR_LANGUAGES are also in the list
export const OTHER_LANGUAGES = ALL_LANGUAGES.filter(
  lang => !POPULAR_LANGUAGES.some(pop => pop.code === lang.code)
).sort((a, b) => a.name.localeCompare(b.name));
